### ISSUE TITLE
No Formatting in Plain Text Output

### ISSUE THREAD

**Issue by peterjschroeder** [adbar/trafilatura#48]
When using include_formatting for plain text, I'm not seeing any formatting (bold, italics, etc..).
The term I'm using supports this. Is this by design or a bug?
I tried both the standalone version and using it as a library with trafilatura.extract(downloaded, include_formatting=True).

**Comment by adbar** [comment]
Hi, since this kind of output contains plain text only there is currently no way to take formatting into account. As you remark using `include_formatting=True` doesn't affect the output. I suggest you use XML as output to keep the document structure.

**Comment by peterjschroeder** [comment]
Okay, thank you. I'll have to parse it on my own. It probably is the best route anyways as the text output drops image urls, which I'd like to keep.

**Comment by adbar** [comment]
Text output could include image URLs if it's what the user wants by setting `include_images` to `True`. I have no time to implement it right now but I'll re-open the issue to keep track of it.

**Comment by peterjschroeder** [comment]
I had previously tried include_images, but not only am I not seeing the urls included, but it stops further use for some reason until I restart my program. This is using trafilatura as a library in python.

My goal is to get the text with bold/italics/colors (as ansi), parse the image url and convert it to sixel inline, than send it out to a pager (less -r).

**Comment by adbar** [comment]
The bug happening when you run the library with `include_images` isn't normal. Could you please copy the error message here?

**Comment by peterjschroeder** [comment]
It doesn't shoot out an error message.

With include_images, trafilatura.extract just gets None after the first use. Even if later trying to use it on the first url that had previously worked.

Now what is odd, trafilatura.fetch_url still works at this point. I tested this by printing the variables I assigned to them.

If I remove include_images from trafilatura.extract, everything works as it should.

Here is my code.
https://github.com/peterjschroeder/googlit

**Comment by adbar** [comment]
It could be related to this bug: https://github.com/adbar/trafilatura/issues/51, which is now solved. Have you tried installing the latest version from the repository?
`pip3 install -U git+https://github.com/adbar/trafilatura`

**Comment by peterjschroeder** [comment]
That fix allowed trafilatura to continue to work with include_images after the first, but I still see no image urls.

**Comment by adbar** [comment]
That's correct, the image information wasn't passed to the TXT output although it was there as XML. I fixed it in bfdc9d47b4f60a79fb39e609bfab5a411a95d453.
Does it correspond to what you were expecting?

**Comment by peterjschroeder** [comment]
Yes, that fix worked. Thank you.

On the original question. Would you be willing to accept a pull request for a text_enhanced output, if I were to implement it?

Currently I have it working in my own code, but it's pretty hacky.
After trafilatura.fetch_url, I replace the tags with custom tags (ex. **boldstart**), than after trafilatura.extract I replace the custom tags with the ansi code (ex. \033[1m).

It would be a lot cleaner if instead the bold, italic, and color tags were not stripped. Than they could easily be replaced with the corresponding ansi codes. Another idea is a keep_tags option. That could cover images, bold, italics, or whatever else someone may want to keep to parse on their own.

**Comment by adbar** [comment]
I get your point but I think ANSI code is too specific. I opted for markdown annotations in dd7d7f52d02559ca0137334f71d89359a742774c. It's not covered by the tests yet, does it work for you?

The `keep_tags` option is a good idea, so far the tags concerning font and color are not taken into account.

**Comment by peterjschroeder** [comment]
That works, thank you. I went with this to get it to ansi.

`
def markdown2ansi(text):
    text = markdown.markdown(text).replace('\<p\>', '').replace('\</p\>')

    replacements = [('(<strong>)', r'\033[1m'), ('(</strong>)', r'\033[0m'), ('(<em>)', r'\033[3m'),
            ('(</em>)', r'\033[0m'), ('(<ins>)', r'\033[4m'), ('(</ins>)', r'\033[0m'), ('(<del>)',
            r'\033[9m'), ('(</del>)', r'\033[0m')]

    for htag, eseq in replacements:
        text = re.sub(htag, eseq, text, flags=re.MULTILINE)

    return text

Question on the color. Is the color already being stored in xml. If so, can we just not strip \<span color ='blue'>. Markdown allows this from what I've read.

Also (sorry for jumping around), I noticed some image urls are missing the beginning of the url (Wikipedia for example). Could a check be made looking for urls that start with / and if so append the side address?

Thank You for all your help.
`

**Comment by adbar** [comment]
Hi, thanks for the feedback, I'm closing this issue now and will continue working on the remaining questions in separate threads.
Please don't hesitate to file issues if you find bugs.
